### ISSUE TITLE
buildable when?

### ISSUE THREAD

**Issue by PotatoSUS** [PlutoSolutions/AbyssOSS#1]
buildable when?buildable when?buildable when?buildable when?buildable when?buildable when?buildable when?buildable when?buildable when?buildable when?

**Comment by cattyngmd** [comment]
never

**Comment by mr-nv** [comment]
we are not gonna work on this again, feel free to make that shit buildable yourself

**Comment by MacTonight4967** [comment]
could you help fix some errors in my buildable source of a deob? I mean if you dont want to work on that one. then why cant you just hand off the code to someone else. i have a github. if you want to work on making a buildable for me come to me. weill do it for the sake of people using our client, i think if you just saw my deobs you would consider to work on achieving the buildable deobfuscated code that alot of 2b2t builders want. come to my github at https://github.com/MacTonight4967/nhack-1.9.0 for more information. its not finished and its the only deob that i think i can make into a buildable.
